#!/bin/bash
# ==========================================
# 系统快照备份工具 卸载脚本
# ==========================================

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
RESET="\033[0m"

echo -e "${YELLOW}🗑 开始卸载系统快照备份工具...${RESET}"

# 停止并禁用 systemd 服务和定时器
systemctl stop system-snapshot.timer 2>/dev/null
systemctl disable system-snapshot.timer 2>/dev/null
systemctl stop system-snapshot.service 2>/dev/null
systemctl disable system-snapshot.service 2>/dev/null

# 删除 systemd 配置文件
rm -f /etc/systemd/system/system-snapshot.service
rm -f /etc/systemd/system/system-snapshot.timer
systemctl daemon-reload
systemctl reset-failed

# 删除主脚本和配置文件
rm -f /root/system_snapshot.sh
rm -f /root/snapshot_config.conf

# 删除日志文件
rm -f /root/snapshot_log.log
rm -f /root/snapshot_debug.log
rm -f /root/snapshot_install.log

# 删除本地备份目录（如果存在）
if [ -d "/backups" ]; then
    echo -e "${YELLOW}是否删除本地备份目录 /backups ? (y/N)${RESET}"
    read -r CONFIRM
    if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
        rm -rf /backups
        echo -e "${GREEN}✓ 已删除 /backups${RESET}"
    else
        echo -e "${YELLOW}⚠ 已保留 /backups${RESET}"
    fi
fi

# 删除 SSH key（如果是专门生成的）
if [ -f "/root/.ssh/id_rsa" ] && grep -q "Generated by snapshot tool" /root/.ssh/id_rsa.pub 2>/dev/null; then
    echo -e "${YELLOW}是否删除 /root/.ssh/id_rsa (用于快照工具的 SSH key)? (y/N)${RESET}"
    read -r CONFIRM_KEY
    if [[ "$CONFIRM_KEY" =~ ^[Yy]$ ]]; then
        rm -f /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
        echo -e "${GREEN}✓ 已删除 SSH key${RESET}"
    else
        echo -e "${YELLOW}⚠ 已保留 SSH key${RESET}"
    fi
fi

echo -e "${GREEN}✅ 系统快照备份工具已卸载完成${RESET}"
